### PR TITLE
Using r-lib GitHub actions

### PR DESCRIPTION
**Pull request by AlbanSagouis**
## Description
Going toward replacing the existing GitHub actions workflow which has errors (fix attempt in progress) with a more standard workflow prepared by r-lib. When comparing both workflow, special attention should be given to documentation, test coverage and badges.

## Related Issue
This work was motivated by a comment and recommendation by @maelle in #37

### CODE REVIEW

**Comment by maelle** [comment]
Reg documentation, you don't have to build the pkgdown website as it's built centrally cf https://ropensci.org/blog/2021/09/03/runiverse-docs/ + https://ropensci.org/blog/2019/06/07/ropensci-docs/

**Comment by maelle** [comment]
@AlbanSagouis There was _just_ new release of r-lib/actions :sweat_smile: https://twitter.com/GaborCsardi/status/1470706718707523585

**Comment by AlbanSagouis** [comment]
> Reg documentation, you don't have to build the pkgdown website as it's built centrally cf https://ropensci.org/blog/2021/09/03/runiverse-docs/ + https://ropensci.org/blog/2019/06/07/ropensci-docs/

Thanks @maelle for the links, I see that r-universe workflows are ran indeed when code is pushed to the the master branch and that your correction in PR #37 fixed workflow `pkgdown-docs`. Now, are these "documents" built somewhere else in the package workflow? I don't see where.

Other question: I thought that updating badges was part of the workflow sent to GitHub Actions but it is actually done only locally when knitting the readme.Rmd, is that right? What about test coverage though?


> @AlbanSagouis There was _just_ new release of r-lib/actions 😅 https://twitter.com/GaborCsardi/status/1470706718707523585

Thanks a lot, great timing! 2ec89c0

**Comment by maelle** [comment]
The website is only built in the central stuff, not in your repo indeed, I just wondered whether you were planning to add that (which would then be useless).

Reg badges
* check their URL;
* it can be some sort of caching problem.

I wish I had been able to mention the v2 release _before_ you started all this work though, that would have been even better timing :wink:

**Pull request merged**
